### ISSUE TITLE
allow users to pass arbitrary props to each div spinner component

### ISSUE THREAD

**Issue by ajwann** [ajwann/css-spinners-react#14]
Each spinner is just a ```div``` element with a css class applied. Since using inline css styles is popular in the React world, it would be nice to support this by letting users pass arbitrary props to be set on these ```div``` elements.

Users would pass props like so:
```js
<Dots style="width:100px;" ...props />
```

Each spinner will need to be updated to just apply any props passed into it via use of the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax). For example, the ```Dots``` component would look something like:
```js
// whatever imports each component currently have should stay the same

const Dots = (props) => {
  render(
    <div className="dots-loader" ...props />
    </div>
  )
}
```

**Comment by danditomaso** [comment]
Hey, I'd like to take this issue on. I'll be opening a PR for with the fix shortly. Thanks for the excellent detail in the original issue description.

**Comment by ajwann** [comment]
No problem @danditomaso, thanks for your help!

**Comment by jamesdbruner** [comment]
Hey @ajwann and @danditomaso 
I realize this PR is closed but wanted to point out that you could simply these components even further. You could turn this

```javascript
const Atebits = props => {
  return(
    <div className="atebits-loader" {...props} />
  )
}
```

Into this
```javascript
const Atebits = props => <div className="atebits-loader" {...props} />
```
This is entirely subjective but I think it's much easier to read with the implicit return.

**Comment by jamesdbruner** [comment]
Oh, one more thing... You can consolidate the component export to look something like this

```javascript
export const Atebits = props => <div className="atebits-loader" {...props} />
```
